upstream vproapp {
 server vproapp:8080;
}
server {
  listen 80;
location / {
  proxy_pass http://vproapp;
}
}

#41

#How It Works
#Step	Action
#1️	Client sends a request to http://your-server/.
#2	Nginx receives the request on port 80.
#3	Nginx forwards it to the upstream server (vproapp:8080).
#4	The backend (vproapp) processes the request and returns a response.
#5	Nginx sends the response back to the client.

# Acts as a Reverse Proxy
#- Forwards requests from port 80 to a backend (vproapp:8080)
#- Can be extended with load balancing, WebSockets, or SSL